clone_depth: 1

image:
  - Visual Studio 2019

environment:
  PYTHON: "C:\\Python37-x64"

  matrix:
#    Python 2.x builds do not work because implementation of os.readlink did not support Windows till 3.2
    - TOXENV: "py34"
    - TOXENV: "py35"
    - TOXENV: "py36"
    - TOXENV: "py37"

matrix:
  fast_finish: true

build: off

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --upgrade wheel>=0.30.0 setuptools>=36.6.0"
  - "%PYTHON%\\python.exe -m pip install -r appveyor-requirements.txt"

test_script:
  - "%PYTHON%\\python.exe -m tox -vv -- --cov-report=xml"

after_test:
  - "%PYTHON%\\python.exe -m codecov --required --file %APPVEYOR_BUILD_FOLDER%\\coverage.xml"
